// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/golifez/zkit/internal/data/ent/aws_iam"
	"github.com/golifez/zkit/internal/data/ent/predicate"
)

// AWSIamQuery is the builder for querying Aws_iam entities.
type AWSIamQuery struct {
	config
	ctx        *QueryContext
	order      []aws_iam.OrderOption
	inters     []Interceptor
	predicates []predicate.Aws_iam
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AWSIamQuery builder.
func (aiq *AWSIamQuery) Where(ps ...predicate.Aws_iam) *AWSIamQuery {
	aiq.predicates = append(aiq.predicates, ps...)
	return aiq
}

// Limit the number of records to be returned by this query.
func (aiq *AWSIamQuery) Limit(limit int) *AWSIamQuery {
	aiq.ctx.Limit = &limit
	return aiq
}

// Offset to start from.
func (aiq *AWSIamQuery) Offset(offset int) *AWSIamQuery {
	aiq.ctx.Offset = &offset
	return aiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aiq *AWSIamQuery) Unique(unique bool) *AWSIamQuery {
	aiq.ctx.Unique = &unique
	return aiq
}

// Order specifies how the records should be ordered.
func (aiq *AWSIamQuery) Order(o ...aws_iam.OrderOption) *AWSIamQuery {
	aiq.order = append(aiq.order, o...)
	return aiq
}

// First returns the first Aws_iam entity from the query.
// Returns a *NotFoundError when no Aws_iam was found.
func (aiq *AWSIamQuery) First(ctx context.Context) (*Aws_iam, error) {
	nodes, err := aiq.Limit(1).All(setContextOp(ctx, aiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{aws_iam.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aiq *AWSIamQuery) FirstX(ctx context.Context) *Aws_iam {
	node, err := aiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Aws_iam ID from the query.
// Returns a *NotFoundError when no Aws_iam ID was found.
func (aiq *AWSIamQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(1).IDs(setContextOp(ctx, aiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{aws_iam.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aiq *AWSIamQuery) FirstIDX(ctx context.Context) int {
	id, err := aiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Aws_iam entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Aws_iam entity is found.
// Returns a *NotFoundError when no Aws_iam entities are found.
func (aiq *AWSIamQuery) Only(ctx context.Context) (*Aws_iam, error) {
	nodes, err := aiq.Limit(2).All(setContextOp(ctx, aiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{aws_iam.Label}
	default:
		return nil, &NotSingularError{aws_iam.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aiq *AWSIamQuery) OnlyX(ctx context.Context) *Aws_iam {
	node, err := aiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Aws_iam ID in the query.
// Returns a *NotSingularError when more than one Aws_iam ID is found.
// Returns a *NotFoundError when no entities are found.
func (aiq *AWSIamQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(2).IDs(setContextOp(ctx, aiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{aws_iam.Label}
	default:
		err = &NotSingularError{aws_iam.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aiq *AWSIamQuery) OnlyIDX(ctx context.Context) int {
	id, err := aiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Aws_iams.
func (aiq *AWSIamQuery) All(ctx context.Context) ([]*Aws_iam, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryAll)
	if err := aiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Aws_iam, *AWSIamQuery]()
	return withInterceptors[[]*Aws_iam](ctx, aiq, qr, aiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aiq *AWSIamQuery) AllX(ctx context.Context) []*Aws_iam {
	nodes, err := aiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Aws_iam IDs.
func (aiq *AWSIamQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aiq.ctx.Unique == nil && aiq.path != nil {
		aiq.Unique(true)
	}
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryIDs)
	if err = aiq.Select(aws_iam.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aiq *AWSIamQuery) IDsX(ctx context.Context) []int {
	ids, err := aiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aiq *AWSIamQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryCount)
	if err := aiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aiq, querierCount[*AWSIamQuery](), aiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aiq *AWSIamQuery) CountX(ctx context.Context) int {
	count, err := aiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aiq *AWSIamQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aiq.ctx, ent.OpQueryExist)
	switch _, err := aiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aiq *AWSIamQuery) ExistX(ctx context.Context) bool {
	exist, err := aiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AWSIamQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aiq *AWSIamQuery) Clone() *AWSIamQuery {
	if aiq == nil {
		return nil
	}
	return &AWSIamQuery{
		config:     aiq.config,
		ctx:        aiq.ctx.Clone(),
		order:      append([]aws_iam.OrderOption{}, aiq.order...),
		inters:     append([]Interceptor{}, aiq.inters...),
		predicates: append([]predicate.Aws_iam{}, aiq.predicates...),
		// clone intermediate query.
		sql:  aiq.sql.Clone(),
		path: aiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UID string `json:"uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AWSIam.Query().
//		GroupBy(aws_iam.FieldUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aiq *AWSIamQuery) GroupBy(field string, fields ...string) *AWSIamGroupBy {
	aiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AWSIamGroupBy{build: aiq}
	grbuild.flds = &aiq.ctx.Fields
	grbuild.label = aws_iam.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UID string `json:"uid,omitempty"`
//	}
//
//	client.AWSIam.Query().
//		Select(aws_iam.FieldUID).
//		Scan(ctx, &v)
func (aiq *AWSIamQuery) Select(fields ...string) *AWSIamSelect {
	aiq.ctx.Fields = append(aiq.ctx.Fields, fields...)
	sbuild := &AWSIamSelect{AWSIamQuery: aiq}
	sbuild.label = aws_iam.Label
	sbuild.flds, sbuild.scan = &aiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AWSIamSelect configured with the given aggregations.
func (aiq *AWSIamQuery) Aggregate(fns ...AggregateFunc) *AWSIamSelect {
	return aiq.Select().Aggregate(fns...)
}

func (aiq *AWSIamQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aiq); err != nil {
				return err
			}
		}
	}
	for _, f := range aiq.ctx.Fields {
		if !aws_iam.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aiq.path != nil {
		prev, err := aiq.path(ctx)
		if err != nil {
			return err
		}
		aiq.sql = prev
	}
	return nil
}

func (aiq *AWSIamQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Aws_iam, error) {
	var (
		nodes = []*Aws_iam{}
		_spec = aiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Aws_iam).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Aws_iam{config: aiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aiq *AWSIamQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aiq.querySpec()
	_spec.Node.Columns = aiq.ctx.Fields
	if len(aiq.ctx.Fields) > 0 {
		_spec.Unique = aiq.ctx.Unique != nil && *aiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aiq.driver, _spec)
}

func (aiq *AWSIamQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(aws_iam.Table, aws_iam.Columns, sqlgraph.NewFieldSpec(aws_iam.FieldID, field.TypeInt))
	_spec.From = aiq.sql
	if unique := aiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aiq.path != nil {
		_spec.Unique = true
	}
	if fields := aiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aws_iam.FieldID)
		for i := range fields {
			if fields[i] != aws_iam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aiq *AWSIamQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aiq.driver.Dialect())
	t1 := builder.Table(aws_iam.Table)
	columns := aiq.ctx.Fields
	if len(columns) == 0 {
		columns = aws_iam.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aiq.sql != nil {
		selector = aiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aiq.ctx.Unique != nil && *aiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aiq.predicates {
		p(selector)
	}
	for _, p := range aiq.order {
		p(selector)
	}
	if offset := aiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AWSIamGroupBy is the group-by builder for Aws_iam entities.
type AWSIamGroupBy struct {
	selector
	build *AWSIamQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aigb *AWSIamGroupBy) Aggregate(fns ...AggregateFunc) *AWSIamGroupBy {
	aigb.fns = append(aigb.fns, fns...)
	return aigb
}

// Scan applies the selector query and scans the result into the given value.
func (aigb *AWSIamGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aigb.build.ctx, ent.OpQueryGroupBy)
	if err := aigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AWSIamQuery, *AWSIamGroupBy](ctx, aigb.build, aigb, aigb.build.inters, v)
}

func (aigb *AWSIamGroupBy) sqlScan(ctx context.Context, root *AWSIamQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aigb.fns))
	for _, fn := range aigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aigb.flds)+len(aigb.fns))
		for _, f := range *aigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AWSIamSelect is the builder for selecting fields of AWSIam entities.
type AWSIamSelect struct {
	*AWSIamQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ais *AWSIamSelect) Aggregate(fns ...AggregateFunc) *AWSIamSelect {
	ais.fns = append(ais.fns, fns...)
	return ais
}

// Scan applies the selector query and scans the result into the given value.
func (ais *AWSIamSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ais.ctx, ent.OpQuerySelect)
	if err := ais.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AWSIamQuery, *AWSIamSelect](ctx, ais.AWSIamQuery, ais, ais.inters, v)
}

func (ais *AWSIamSelect) sqlScan(ctx context.Context, root *AWSIamQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ais.fns))
	for _, fn := range ais.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ais.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ais.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
