// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/golifez/zkit/internal/data/ent/aws_iam"
	"github.com/golifez/zkit/internal/data/ent/predicate"
)

// AWSIamDelete is the builder for deleting a Aws_iam entity.
type AWSIamDelete struct {
	config
	hooks    []Hook
	mutation *AWSIamMutation
}

// Where appends a list predicates to the AWSIamDelete builder.
func (aid *AWSIamDelete) Where(ps ...predicate.Aws_iam) *AWSIamDelete {
	aid.mutation.Where(ps...)
	return aid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aid *AWSIamDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, aid.sqlExec, aid.mutation, aid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (aid *AWSIamDelete) ExecX(ctx context.Context) int {
	n, err := aid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aid *AWSIamDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aws_iam.Table, sqlgraph.NewFieldSpec(aws_iam.FieldID, field.TypeInt))
	if ps := aid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	aid.mutation.done = true
	return affected, err
}

// AWSIamDeleteOne is the builder for deleting a single Aws_iam entity.
type AWSIamDeleteOne struct {
	aid *AWSIamDelete
}

// Where appends a list predicates to the AWSIamDelete builder.
func (aido *AWSIamDeleteOne) Where(ps ...predicate.Aws_iam) *AWSIamDeleteOne {
	aido.aid.mutation.Where(ps...)
	return aido
}

// Exec executes the deletion query.
func (aido *AWSIamDeleteOne) Exec(ctx context.Context) error {
	n, err := aido.aid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aws_iam.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aido *AWSIamDeleteOne) ExecX(ctx context.Context) {
	if err := aido.Exec(ctx); err != nil {
		panic(err)
	}
}
