// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/golifez/zkit/internal/data/ent/aws_iam"
	"github.com/golifez/zkit/internal/data/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAWSIam = "Aws_iam"
)

// AWSIamMutation represents an operation that mutates the Aws_iam nodes in the graph.
type AWSIamMutation struct {
	config
	op            Op
	typ           string
	id            *int
	uid           *string
	account_id    *string
	iam_name      *string
	access_key    *string
	secret_key    *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Aws_iam, error)
	predicates    []predicate.Aws_iam
}

var _ ent.Mutation = (*AWSIamMutation)(nil)

// awsIamOption allows management of the mutation configuration using functional options.
type awsIamOption func(*AWSIamMutation)

// newAWSIamMutation creates new mutation for the Aws_iam entity.
func newAWSIamMutation(c config, op Op, opts ...awsIamOption) *AWSIamMutation {
	m := &AWSIamMutation{
		config:        c,
		op:            op,
		typ:           TypeAWSIam,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAws_iamID sets the ID field of the mutation.
func withAws_iamID(id int) awsIamOption {
	return func(m *AWSIamMutation) {
		var (
			err   error
			once  sync.Once
			value *Aws_iam
		)
		m.oldValue = func(ctx context.Context) (*Aws_iam, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Aws_iam.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAws_iam sets the old Aws_iam of the mutation.
func withAws_iam(node *Aws_iam) awsIamOption {
	return func(m *AWSIamMutation) {
		m.oldValue = func(context.Context) (*Aws_iam, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AWSIamMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AWSIamMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AWSIamMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AWSIamMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Aws_iam.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *AWSIamMutation) SetUID(s string) {
	m.uid = &s
}

// UID returns the value of the "uid" field in the mutation.
func (m *AWSIamMutation) UID() (r string, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// ResetUID resets all changes to the "uid" field.
func (m *AWSIamMutation) ResetUID() {
	m.uid = nil
}

// SetAccountID sets the "account_id" field.
func (m *AWSIamMutation) SetAccountID(s string) {
	m.account_id = &s
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *AWSIamMutation) AccountID() (r string, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldAccountID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *AWSIamMutation) ResetAccountID() {
	m.account_id = nil
}

// SetIamName sets the "iam_name" field.
func (m *AWSIamMutation) SetIamName(s string) {
	m.iam_name = &s
}

// IamName returns the value of the "iam_name" field in the mutation.
func (m *AWSIamMutation) IamName() (r string, exists bool) {
	v := m.iam_name
	if v == nil {
		return
	}
	return *v, true
}

// OldIamName returns the old "iam_name" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldIamName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIamName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIamName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIamName: %w", err)
	}
	return oldValue.IamName, nil
}

// ResetIamName resets all changes to the "iam_name" field.
func (m *AWSIamMutation) ResetIamName() {
	m.iam_name = nil
}

// SetAccessKey sets the "access_key" field.
func (m *AWSIamMutation) SetAccessKey(s string) {
	m.access_key = &s
}

// AccessKey returns the value of the "access_key" field in the mutation.
func (m *AWSIamMutation) AccessKey() (r string, exists bool) {
	v := m.access_key
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessKey returns the old "access_key" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldAccessKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessKey: %w", err)
	}
	return oldValue.AccessKey, nil
}

// ResetAccessKey resets all changes to the "access_key" field.
func (m *AWSIamMutation) ResetAccessKey() {
	m.access_key = nil
}

// SetSecretKey sets the "secret_key" field.
func (m *AWSIamMutation) SetSecretKey(s string) {
	m.secret_key = &s
}

// SecretKey returns the value of the "secret_key" field in the mutation.
func (m *AWSIamMutation) SecretKey() (r string, exists bool) {
	v := m.secret_key
	if v == nil {
		return
	}
	return *v, true
}

// OldSecretKey returns the old "secret_key" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldSecretKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSecretKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSecretKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSecretKey: %w", err)
	}
	return oldValue.SecretKey, nil
}

// ResetSecretKey resets all changes to the "secret_key" field.
func (m *AWSIamMutation) ResetSecretKey() {
	m.secret_key = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AWSIamMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AWSIamMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AWSIamMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AWSIamMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AWSIamMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Aws_iam entity.
// If the Aws_iam object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AWSIamMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AWSIamMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the AWSIamMutation builder.
func (m *AWSIamMutation) Where(ps ...predicate.Aws_iam) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AWSIamMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AWSIamMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Aws_iam, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AWSIamMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AWSIamMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Aws_iam).
func (m *AWSIamMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AWSIamMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.uid != nil {
		fields = append(fields, aws_iam.FieldUID)
	}
	if m.account_id != nil {
		fields = append(fields, aws_iam.FieldAccountID)
	}
	if m.iam_name != nil {
		fields = append(fields, aws_iam.FieldIamName)
	}
	if m.access_key != nil {
		fields = append(fields, aws_iam.FieldAccessKey)
	}
	if m.secret_key != nil {
		fields = append(fields, aws_iam.FieldSecretKey)
	}
	if m.created_at != nil {
		fields = append(fields, aws_iam.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, aws_iam.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AWSIamMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case aws_iam.FieldUID:
		return m.UID()
	case aws_iam.FieldAccountID:
		return m.AccountID()
	case aws_iam.FieldIamName:
		return m.IamName()
	case aws_iam.FieldAccessKey:
		return m.AccessKey()
	case aws_iam.FieldSecretKey:
		return m.SecretKey()
	case aws_iam.FieldCreatedAt:
		return m.CreatedAt()
	case aws_iam.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AWSIamMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case aws_iam.FieldUID:
		return m.OldUID(ctx)
	case aws_iam.FieldAccountID:
		return m.OldAccountID(ctx)
	case aws_iam.FieldIamName:
		return m.OldIamName(ctx)
	case aws_iam.FieldAccessKey:
		return m.OldAccessKey(ctx)
	case aws_iam.FieldSecretKey:
		return m.OldSecretKey(ctx)
	case aws_iam.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case aws_iam.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Aws_iam field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AWSIamMutation) SetField(name string, value ent.Value) error {
	switch name {
	case aws_iam.FieldUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case aws_iam.FieldAccountID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case aws_iam.FieldIamName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIamName(v)
		return nil
	case aws_iam.FieldAccessKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessKey(v)
		return nil
	case aws_iam.FieldSecretKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSecretKey(v)
		return nil
	case aws_iam.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case aws_iam.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Aws_iam field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AWSIamMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AWSIamMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AWSIamMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Aws_iam numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AWSIamMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AWSIamMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AWSIamMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Aws_iam nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AWSIamMutation) ResetField(name string) error {
	switch name {
	case aws_iam.FieldUID:
		m.ResetUID()
		return nil
	case aws_iam.FieldAccountID:
		m.ResetAccountID()
		return nil
	case aws_iam.FieldIamName:
		m.ResetIamName()
		return nil
	case aws_iam.FieldAccessKey:
		m.ResetAccessKey()
		return nil
	case aws_iam.FieldSecretKey:
		m.ResetSecretKey()
		return nil
	case aws_iam.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case aws_iam.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Aws_iam field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AWSIamMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AWSIamMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AWSIamMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AWSIamMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AWSIamMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AWSIamMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AWSIamMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Aws_iam unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AWSIamMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Aws_iam edge %s", name)
}
