// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/golifez/zkit/internal/data/ent/aws_iam"
	"github.com/golifez/zkit/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aws_iamFields := schema.Aws_iam{}.Fields()
	_ = aws_iamFields
	// aws_iamDescCreatedAt is the schema descriptor for created_at field.
	aws_iamDescCreatedAt := aws_iamFields[5].Descriptor()
	// aws_iam.DefaultCreatedAt holds the default value on creation for the created_at field.
	aws_iam.DefaultCreatedAt = aws_iamDescCreatedAt.Default.(func() time.Time)
	// aws_iamDescUpdatedAt is the schema descriptor for updated_at field.
	aws_iamDescUpdatedAt := aws_iamFields[6].Descriptor()
	// aws_iam.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	aws_iam.DefaultUpdatedAt = aws_iamDescUpdatedAt.Default.(func() time.Time)
}
