// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/aws/v1/iam.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建角色
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwsService    string                 `protobuf:"bytes,1,opt,name=AwsService,proto3" json:"AwsService,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	RoleDesc      string                 `protobuf:"bytes,3,opt,name=RoleDesc,proto3" json:"RoleDesc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_api_aws_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aws_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_aws_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetAwsService() string {
	if x != nil {
		return x.AwsService
	}
	return ""
}

func (x *CreateRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleRequest) GetRoleDesc() string {
	if x != nil {
		return x.RoleDesc
	}
	return ""
}

type CreateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReply) Reset() {
	*x = CreateRoleReply{}
	mi := &file_api_aws_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReply) ProtoMessage() {}

func (x *CreateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aws_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReply.ProtoReflect.Descriptor instead.
func (*CreateRoleReply) Descriptor() ([]byte, []int) {
	return file_api_aws_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 添加AK秘钥
type AddAkSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AconutId      string                 `protobuf:"bytes,1,opt,name=AconutId,proto3" json:"AconutId,omitempty"`
	AccessKey     string                 `protobuf:"bytes,2,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAkSecretRequest) Reset() {
	*x = AddAkSecretRequest{}
	mi := &file_api_aws_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAkSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAkSecretRequest) ProtoMessage() {}

func (x *AddAkSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aws_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAkSecretRequest.ProtoReflect.Descriptor instead.
func (*AddAkSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_aws_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *AddAkSecretRequest) GetAconutId() string {
	if x != nil {
		return x.AconutId
	}
	return ""
}

func (x *AddAkSecretRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AddAkSecretRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type AddAkSecretReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAkSecretReply) Reset() {
	*x = AddAkSecretReply{}
	mi := &file_api_aws_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAkSecretReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAkSecretReply) ProtoMessage() {}

func (x *AddAkSecretReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aws_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAkSecretReply.ProtoReflect.Descriptor instead.
func (*AddAkSecretReply) Descriptor() ([]byte, []int) {
	return file_api_aws_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *AddAkSecretReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_aws_v1_iam_proto protoreflect.FileDescriptor

const file_api_aws_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x14api/aws/v1/iam.proto\x12\x06aws.v1\"k\n" +
	"\x11CreateRoleRequest\x12\x1e\n" +
	"\n" +
	"AwsService\x18\x01 \x01(\tR\n" +
	"AwsService\x12\x1a\n" +
	"\bRoleName\x18\x02 \x01(\tR\bRoleName\x12\x1a\n" +
	"\bRoleDesc\x18\x03 \x01(\tR\bRoleDesc\"+\n" +
	"\x0fCreateRoleReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"l\n" +
	"\x12AddAkSecretRequest\x12\x1a\n" +
	"\bAconutId\x18\x01 \x01(\tR\bAconutId\x12\x1c\n" +
	"\tAccessKey\x18\x02 \x01(\tR\tAccessKey\x12\x1c\n" +
	"\tSecretKey\x18\x03 \x01(\tR\tSecretKey\",\n" +
	"\x10AddAkSecretReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x93\x01\n" +
	"\n" +
	"IamService\x12C\n" +
	"\vAddAkSecret\x12\x1a.aws.v1.AddAkSecretRequest\x1a\x18.aws.v1.AddAkSecretReply\x12@\n" +
	"\n" +
	"CreateRole\x12\x19.aws.v1.CreateRoleRequest\x1a\x17.aws.v1.CreateRoleReplyB'Z%github.com/golifez/zkit/api/aws/v1;v1b\x06proto3"

var (
	file_api_aws_v1_iam_proto_rawDescOnce sync.Once
	file_api_aws_v1_iam_proto_rawDescData []byte
)

func file_api_aws_v1_iam_proto_rawDescGZIP() []byte {
	file_api_aws_v1_iam_proto_rawDescOnce.Do(func() {
		file_api_aws_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aws_v1_iam_proto_rawDesc), len(file_api_aws_v1_iam_proto_rawDesc)))
	})
	return file_api_aws_v1_iam_proto_rawDescData
}

var file_api_aws_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_aws_v1_iam_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),  // 0: aws.v1.CreateRoleRequest
	(*CreateRoleReply)(nil),    // 1: aws.v1.CreateRoleReply
	(*AddAkSecretRequest)(nil), // 2: aws.v1.AddAkSecretRequest
	(*AddAkSecretReply)(nil),   // 3: aws.v1.AddAkSecretReply
}
var file_api_aws_v1_iam_proto_depIdxs = []int32{
	2, // 0: aws.v1.IamService.AddAkSecret:input_type -> aws.v1.AddAkSecretRequest
	0, // 1: aws.v1.IamService.CreateRole:input_type -> aws.v1.CreateRoleRequest
	3, // 2: aws.v1.IamService.AddAkSecret:output_type -> aws.v1.AddAkSecretReply
	1, // 3: aws.v1.IamService.CreateRole:output_type -> aws.v1.CreateRoleReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_aws_v1_iam_proto_init() }
func file_api_aws_v1_iam_proto_init() {
	if File_api_aws_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aws_v1_iam_proto_rawDesc), len(file_api_aws_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aws_v1_iam_proto_goTypes,
		DependencyIndexes: file_api_aws_v1_iam_proto_depIdxs,
		MessageInfos:      file_api_aws_v1_iam_proto_msgTypes,
	}.Build()
	File_api_aws_v1_iam_proto = out.File
	file_api_aws_v1_iam_proto_goTypes = nil
	file_api_aws_v1_iam_proto_depIdxs = nil
}
