// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AWSIamsColumns holds the columns for the "aws_iams" table.
	AWSIamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString},
		{Name: "account_id", Type: field.TypeString},
		{Name: "iam_name", Type: field.TypeString},
		{Name: "access_key", Type: field.TypeString},
		{Name: "secret_key", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// AWSIamsTable holds the schema information for the "aws_iams" table.
	AWSIamsTable = &schema.Table{
		Name:       "aws_iams",
		Columns:    AWSIamsColumns,
		PrimaryKey: []*schema.Column{AWSIamsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AWSIamsTable,
	}
)

func init() {
}
